name: Release

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]'
        required: true
        default: 'patch'

jobs:
  publish-gpr:
    name: Publish to github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com/'

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump versions and release
        run: |
          lerna version ${{ github.event.inputs.new_version }} --yes --conventional-commits --create-release github
          lerna publish from-package --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}