name: TEST TEST
on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set credentials
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: "Use NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://npm.pkg.github.com/'

    - name: "Version and publish"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = develop ]; then
          npx lerna version --conventional-commits --conventional-graduate --conventional-prerelease --preid beta --yes
        else
          npx lerna version --conventional-commits --conventional-graduate --yes --create-release github
        fi

        npx lerna publish from-git --yes
